bedroom_choices = {
  '1':1,
  '2':2,
  '3':3,
  '4':4,
  '5':5,
  '6':6,
  '7':7,
  '8':8,
  '9':9,
  '10':10
  }

price_choices = {
  '100000':'INR 1,00,000',
  '200000':'INR 2,00,000',
  '300000':'INR 3,00,000',
  '400000':'INR 4,00,000',
  '500000':'INR 5,00,000',
  '600000':'INR 6,00,000',
  '700000':'INR 7,00,000',
  '800000':'INR 8,00,000',
  '900000':'INR 9,00,000',
  '1000000':'INR 1M+',
}

state_choices = {
        'AP': 'Andra Pradesh',
        'AR': 'Arunachal Pradesh',
        'AR': 'Assam',
        'BR': 'Bihar',
        'CG': 'Chhattisgarh',
        'GA': 'Goa',
        'GJ': 'Gujarat',
        'HR': 'Haryana',
        'HP': 'Himachal Pradesh',
        'JK': 'Jammu and Kashmir',
        'JH': 'Jharkhand',
        'KA': 'Karnataka',
        'KL': 'Kerala',
        'MP': 'Madya Pradesh',
        'MH': 'Maharashtra',
        'MN': 'Manipur',
        'ML': 'Meghalaya',
        'MZ': 'Mizoram',
        'NL': 'Nagaland',
        'OD': 'Orissa',
        'PB': 'Punjab',
        'RJ': 'Rajasthan',
        'SK': 'Sikkim',
        'TN': 'Tamil Nadu',
        'TS': 'Telagana',
        'TR': 'Tripura',
        'UT': 'Uttaranchal',
        'UP': 'Uttar Pradesh',
        'WB': 'West Bengal',
        'AN': 'Andaman and Nicobar Islands',
        'CH': 'Chandigarh',
        'DD': 'Dadar and Nagar Haveli',
        'DD': 'Daman and Diu',
        'DL': 'Delhi',
        'LD': 'Lakshadeep',
        'PY': 'Pondicherry',
}